"""Future schema changes

Revision ID: 687d4a4e02a9
Revises: 123123abc
Create Date: 2025-01-03 11:04:49.462987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '687d4a4e02a9'
down_revision = '123123abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatflow_temp')
    op.drop_table('chat_logs')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
        batch_op.alter_column('new_repayment',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('monthly_savings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('yearly_savings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('total_savings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('years_saved',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('leads_property_reference_key', type_='unique')
        batch_op.drop_column('property_reference')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('outstanding_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_interest_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remaining_tenure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('original_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('original_tenure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_monthly_payment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('years_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_savings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('yearly_savings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_savings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tenure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('new_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temp_cashout_amount', sa.Float(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('current_step')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_step', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('temp_cashout_amount')
        batch_op.drop_column('new_rate')
        batch_op.drop_column('current_rate')
        batch_op.drop_column('tenure')
        batch_op.drop_column('total_savings')
        batch_op.drop_column('yearly_savings')
        batch_op.drop_column('monthly_savings')
        batch_op.drop_column('years_paid')
        batch_op.drop_column('current_monthly_payment')
        batch_op.drop_column('original_tenure')
        batch_op.drop_column('original_amount')
        batch_op.drop_column('remaining_tenure')
        batch_op.drop_column('current_interest_rate')
        batch_op.drop_column('outstanding_balance')
        batch_op.drop_column('state')
        batch_op.drop_column('language')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_reference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('leads_property_reference_key', ['property_reference'])
        batch_op.alter_column('years_saved',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_savings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('yearly_savings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('monthly_savings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('new_repayment',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))

    op.create_table('chat_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_logs_pkey')
    )
    op.create_table('chatflow_temp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('messenger_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('original_loan_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('original_loan_tenure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_repayment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), server_default=sa.text("'Unknown'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chatflow_temp_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatflow_temp_pkey')
    )
    # ### end Alembic commands ###
